### ISSUE TITLE
Fluid ounces ≠ ounces

### ISSUE THREAD

**Issue by jt196** [jclind/ingredient-unit-converter#1]
I won't bother with a PR, but here's the correct code

```JSON
{
names: [
	'fluid ounce',
	'fluidounce',
	'fluid ounces',
	'fluidounces',
	'fl.oz.',
	'floz',
	'fl.oz',
	'floz.',
	'fl.ozs.',
	'flozs',
	'fl.ozs',
	'flozs.'
],
grams: 29.5735
},
{
names: ['ounce', 'ounces', 'oz.', 'oz', 'ozs.', 'ozs'],
grams: 28.3495
}
```

**Comment by jclind** [comment]
Just discovered that you sent in this issue a while back, sorry for the delay. I've separated the 'fluid ounces' and 'ounces' into two objects with their 'correct' grams (as correct as this code allows the gram measurements to be). Commit [5cf0272](https://github.com/jclind/ingredient-unit-converter/commit/5cf0272e1e864add46f2bb0906439edd1e64e225).

Thanks for the help!
